Modules/FormBuild/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('formbuild')->group(function() {
    Route::resource('build', 'FormBuildController')->middleware('auth');
    Route::get('view', 'FormBuildController@view')->middleware('auth')->name('view');
});

Modules/FormBuild/Entities/FormComponentData.php
<?php

namespace Modules\FormBuild\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormComponentData extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [];
    
    protected static function newFactory()
    {
        return \Modules\FormBuild\Database\factories\FormComponentDataFactory::new();
    }

    public function user() {
        return $this->belongsTo(App\Models\User::class);
    }

    public function form_order() {
        return $this->belongsTo(FormOrder::class);
    }
}

Modules/FormBuild/Entities/FormData.php
<?php

namespace Modules\FormBuild\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormData extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [];
    
    protected static function newFactory()
    {
        return \Modules\FormBuild\Database\factories\FormDataFactory::new();
    }

    public function user() {
        return $this->belongsTo(App\Models\User::class);
    }

    public function form_order() {
        return $this->belongsTo(FormOrder::class);
    }
}

Modules/FormBuild/Entities/FormOrder.php
<?php

namespace Modules\FormBuild\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormOrder extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [];
    
    protected static function newFactory()
    {
        return \Modules\FormBuild\Database\factories\FormOrderFactory::new();
    }

    public function user() {
        return $this->belongsTo(App\Models\User::class);
    }

    public function form_component_data() {
        return $this->hasOne(FormComponentData::class);
    }

    public function form_data() {
        return $this->hasMany(FormData::class);
    }
}

Modules/FormBuild/Http/Controllers/FormBuildController.php
<?php

namespace Modules\FormBuild\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Modules\FormBuild\Entities\FormOrder;
use Modules\FormBuild\Entities\FormComponentData;

class FormBuildController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('formbuild::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('formbuild::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        dd($request->all());
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        $view = FormOrder::whereId($id)->whereUserId(Auth::user()->id)->with('form_component_data')->first();
        return view('formbuild::show', compact('view'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('formbuild::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }

    public function view()
    {
        $views = FormOrder::whereUserId(Auth::user()->id)->get();
        return view('formbuild::view', compact('views'));
    }
}

Modules/FormBuild/Resources/views/index.blade.php
@extends('layouts.master')

@section('css')
@endsection

@section('header')
    Form Builder
@endsection

@section('header_description')
    Index
@endsection

@section('breadcrumb_level')
    Dashboard
@endsection

@section('breadcrumb_here')
    Builder Index
@endsection

@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="box box-solid">
                <div class="box-header with-border">
                    <h3 class="box-title">Tool Bar</h3>
                    <div class="box-tools">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body no-padding">
                    <ul class="nav nav-pills nav-stacked" id="draggable">
                        <li data-type="input"><a href="" onclick="event.preventDefault()"><i class="fa fa-font"></i> Input</a></li>
                        <li data-type="text"><a href="" onclick="event.preventDefault()"><i class="fa fa-keyboard-o"></i> Textarea</a></li>
                        <li data-type="combo"><a href="" onclick="event.preventDefault()"><i class="fa fa-list-ul"></i> Combo Box</a></li>
                        {{-- <li data-type="input"><a href=""><i class="fa fa-calendar-plus-o"></i> Date Picker</a></li> --}}
                        <li data-type="radio"><a href="" onclick="event.preventDefault()"><i class="fa fa-genderless"></i> Radio</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-8" id="droppable_div">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Dynamic Form</h3>
                </div>
                <div class="alert alert-success" role="alert" id="successMsg" style="display: none"></div>
                <div class="alert alert-danger" role="alert" id="errorMsg" style="display: none"></div>
                <div class="box-body">
                    <form action="" method="POST" role="form" id="builder_form" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group exept_this">
                            <label for="form_name" class="col-form-label text-md-end">Name of the Form * : </label>
                            <input id="form_name" name="form_name" class="form-control exept_this" type="text" placeholder="Enter Name"></input>
                        </div>
                        <hr>
                        <div id="droppable">
                        </div>
                        <div class="box-footer">
                            <div class="pull-right">
                                <button type="submit" id="builder_form_btn" class="btn btn-primary"><i class="fa fa-save "></i> Save</button>
                            </div>
                            <button type="reset" class="btn btn-default" id="builder_form_reset"><i class="fa fa-times"></i> Discard</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('js')
    <script src="{{ asset('js/index.js') }}"></script>
@endsection

Modules/FormBuild/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Module FormBuild</title>

       {{-- Laravel Mix - CSS File --}}
       {{-- <link rel="stylesheet" href="{{ mix('css/formbuild.css') }}"> --}}

    </head>
    <body>
        @yield('content')

        {{-- Laravel Mix - JS File --}}
        {{-- <script src="{{ mix('js/formbuild.js') }}"></script> --}}
    </body>
</html>

Modules/FormBuild/Resources/views/show.blade.php
@extends('layouts.master')

@section('css')
@endsection

@section('header')
    Form Show
@endsection

@section('header_description')
    {{$view->name}}
@endsection

@section('breadcrumb_level')
    Dashboard
@endsection

@section('breadcrumb_here')
    Builder {{$view->name}}
@endsection

@section('content')
<div class="row">
    <div class="col-md-10">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{$view->name}}</h3>
            </div>
            <div class="alert alert-success" role="alert" id="successMsg" style="display: none"></div>
            <div class="alert alert-danger" role="alert" id="errorMsg" style="display: none"></div>
            <div class="box-body">
                <form action="" method="POST" role="form" id="builder_save_form" enctype="multipart/form-data">
                    @php
                        $sort_order = json_decode($view->component_sort_order, true);
                        $form_component_data = json_decode($view->form_component_data->component_data, true);
                    @endphp
                    @foreach ($form_component_data as $key => $components)
                        @if (strtok($key, "_") == 'text' || strtok($key, "_") == 'date') 
                            <x-formBuild.input id="{{ $components['id'] }}" type="{{ $components['type'] }}" name="{{ $components['name'] }}" placeholder="{{ $components['placeholder'] }}" label="{{ $components['label'] }}" />
                        @endif
                        @if (strtok($key, "_") == 'radio') 
                            <x-formBuild.radio id="{{ $components['id'] }}" name="{{ $components['name'] }}" value="{{ $components['value'] }}" label="{{ $components['label'] }}" />
                        @endif
                        @if (strtok($key, "_") == 'textaria') 
                            <x-formBuild.text-aria id="{{ $components['id'] }}" name="{{ $components['name'] }}" label="{{ $components['label'] }}" />
                        @endif
                        @if (strtok($key, "_") == 'combo') 
                            <x-formBuild.combo-box id="{{ $components['id'] }}" name="{{ $components['name'] }}" label="{{ $components['label'] }}" :texts="array_values($components['texts'])" :values="array_values($components['values'])" ></x-formBuild.combo-box>
                        @endif
                    @endforeach
                    <div class="box-footer">
                        <div class="pull-right">
                            <button type="submit" id="builder_form_save_btn" class="btn btn-primary"><i class="fa fa-save "></i> Save</button>
                        </div>
                        <button type="reset" class="btn btn-default" id="builder_form_save_reset"><i class="fa fa-times"></i> Discard</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script src="{{ asset('js/show.js') }}"></script>
@endsection

Modules/FormBuild/Resources/views/view.blade.php
@extends('layouts.master')

@section('css')
@endsection

@section('header')
    Form View
@endsection

@section('header_description')
    View
@endsection

@section('breadcrumb_level')
    Dashboard
@endsection

@section('breadcrumb_here')
    Builder View
@endsection

@section('content')
<div class="row">
    <div class="col-md-3">
        <div class="box box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Forms</h3>
                <div class="box-tools">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body no-padding">
                <ul class="nav nav-pills nav-stacked" id="draggable">
                    @foreach ($views as $view)
                        <li data-form_id="{{$view->id}}"><a href="{{ route('build.show', $view->id) }}"><i class="fa fa-file"></i> {{$view->name}}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>

</div>
@endsection
@section('js')
    <script src="{{ asset('js/index.js') }}"></script>
@endsection